import type { Metadata } from "next";
import Head from 'next/head'
import Script from 'next/script'
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://dev.probablynull.ca/static/index.css" />
        <Script src="https://dev.probablynull.ca/static/index.js" />
      </head>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
