import type { Metadata } from "next";
import Head from 'next/head'
import Script from 'next/script'
import { Inter } from "next/font/google";
import { BTY_CODE_API_ENDPOINT } from '@/constants';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href={`${BTY_CODE_API_ENDPOINT}/static/index.css`}  crossOrigin="anonymous" />
        {/*
        <Script src={`${BTY_CODE_API_ENDPOINT}/static/index.js`} />
        */}
        <Script src={`${BTY_CODE_API_ENDPOINT}/static/client.js`} strategy="beforeInteractive" crossOrigin="anonymous" />
      </head>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
